const { Client } = require('pg');
require('dotenv').config({ path: '.env.local' });

// NOTE: You need the direct connection string (usually port 5432 or 6543)
// Supabase Format: postgres://postgres:[PASSWORD]@db.[REF].supabase.co:5432/postgres
const CONNECTION_STRING = process.env.DATABASE_URL;

if (!CONNECTION_STRING) {
  console.error('Error: DATABASE_URL is required in .env.local for database migrations.');
  process.exit(1);
}

const client = new Client({
  connectionString: CONNECTION_STRING,
  ssl: { rejectUnauthorized: false } // Required for Supabase
});

const SQL_SCHEMA = `
-- 1. Create tables for static data
CREATE TABLE IF NOT EXISTS public.ingredients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  category TEXT,
  image_url TEXT,
  is_staple BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS public.cocktails (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  instructions TEXT,
  category TEXT,
  image_url TEXT,
  glass TEXT
);

CREATE TABLE IF NOT EXISTS public.cocktail_ingredients (
  cocktail_id BIGINT REFERENCES public.cocktails(id) ON DELETE CASCADE,
  ingredient_id BIGINT REFERENCES public.ingredients(id) ON DELETE CASCADE,
  measure TEXT,
  PRIMARY KEY (cocktail_id, ingredient_id)
);

-- 2. Create Shopping List table
CREATE TABLE IF NOT EXISTS public.shopping_list (
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  ingredient_id BIGINT REFERENCES public.ingredients(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, ingredient_id)
);

-- 3. Enable Security (RLS) - Idempotent checks
ALTER TABLE public.ingredients ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "Allow public read ingredients" ON public.ingredients FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE public.cocktails ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "Allow public read cocktails" ON public.cocktails FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE public.cocktail_ingredients ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "Allow public read cocktail_ingredients" ON public.cocktail_ingredients FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE public.shopping_list ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "Users can manage their shopping list" ON public.shopping_list USING (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 4. Create Indexes
CREATE INDEX IF NOT EXISTS idx_cocktail_ingredients_cocktail ON public.cocktail_ingredients(cocktail_id);
CREATE INDEX IF NOT EXISTS idx_cocktail_ingredients_ingredient ON public.cocktail_ingredients(ingredient_id);
`;

async function runMigration() {
  try {
    console.log('🔌 Connecting to database...');
    await client.connect();
    console.log('⚙️ Running Schema Migration...');
    await client.query(SQL_SCHEMA);
    console.log('✅ Database Schema successfully applied.');
  } catch (err) {
    console.error('❌ Migration failed:', err);
  } finally {
    await client.end();
  }
}

runMigration();